version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    env_file:
      .env
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  nodejs:
    container_name: nodejs
    build: app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 50s docker-entrypoint.sh
    command: ["node", "server.js"]
    depends_on:
      - mysql
    # volumes:
    #   - .:/usr/scr
    # command: ["sleep", "365d"]

  nginx:
    container_name: nginx
    build: nginx
    depends_on:
      - nodejs
    ports:
      - 8080:80

volumes:
  mysql-data: